# Generated by Django 3.0.7 on 2021-04-03 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Business', '0002_auto_20210403_0853'),
        ('Customers', '0006_auto_20210403_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistoryModel',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('transactionName', models.CharField(max_length=200)),
                ('transactionCredit', models.CharField(max_length=200)),
                ('transactionDebit', models.CharField(max_length=20)),
                ('transactionPending', models.CharField(max_length=200)),
                ('creationTime', models.DateField(auto_now_add=True)),
                ('transactionBusiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Business.BusinessModel')),
                ('transactionCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.CustomersModel')),
            ],
        ),
    ]
