# Generated by Django 3.0.7 on 2021-04-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0002_auto_20210403_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistorymodel',
            name='transactionTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
