# Generated by Django 3.0.7 on 2021-04-03 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0003_auto_20210403_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistorymodel',
            name='transactionDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionhistorymodel',
            name='transactionTime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
