# Generated by Django 3.0.7 on 2021-04-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0004_auto_20210403_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistorymodel',
            name='transactionCredit',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionhistorymodel',
            name='transactionDebit',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
