# Generated by Django 3.0.7 on 2021-04-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0005_auto_20210404_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistorymodel',
            name='transactionDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transactionhistorymodel',
            name='transactionTime',
            field=models.TimeField(),
        ),
    ]
