# Generated by Django 3.0.7 on 2021-04-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0006_auto_20210408_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistorymodel',
            name='transactionDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transactionhistorymodel',
            name='transactionTime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
