# Generated by Django 3.0.7 on 2021-03-27 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistoryModel',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('transactionName', models.CharField(max_length=200)),
                ('transactionCredit', models.CharField(max_length=200)),
                ('transactionDebit', models.CharField(max_length=200)),
                ('transactionPending', models.CharField(max_length=200)),
                ('transactionContact', models.CharField(max_length=200)),
                ('creationTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('transactionBusiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Business.BusinessModel')),
            ],
        ),
        migrations.CreateModel(
            name='CustomersModel',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=200)),
                ('customerCredit', models.CharField(max_length=200)),
                ('customerDebit', models.CharField(max_length=200)),
                ('customerPending', models.CharField(max_length=200)),
                ('customerContact', models.CharField(max_length=200)),
                ('creationTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('customerBusiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Business.BusinessModel')),
            ],
        ),
    ]
