# Generated by Django 3.0.7 on 2021-03-30 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistorymodel',
            name='transactionCustomer',
            field=models.ForeignKey(default=61, on_delete=django.db.models.deletion.CASCADE, to='Customers.CustomersModel'),
            preserve_default=False,
        ),
    ]
