# Generated by Django 3.0.7 on 2021-03-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0003_auto_20210331_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistorymodel',
            name='creationTime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
