# Generated by Django 3.0.7 on 2021-03-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_auto_20210331_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistorymodel',
            name='transactionDebit',
        ),
        migrations.AddField(
            model_name='transactionhistorymodel',
            name='transactionNewDebit',
            field=models.CharField(default=23, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhistorymodel',
            name='transactionTotalDebit',
            field=models.CharField(default=233, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionhistorymodel',
            name='transactionContact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
