# Generated by Django 3.0.7 on 2021-04-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0005_auto_20210331_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersmodel',
            name='customerDOB',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='TransactionHistoryModel',
        ),
    ]
