# Generated by Django 3.0.7 on 2021-04-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0008_auto_20210404_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersmodel',
            name='customerCredit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customersmodel',
            name='customerDebit',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customersmodel',
            name='customerPending',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
