# Generated by Django 3.0.7 on 2021-04-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0009_auto_20210404_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersmodel',
            name='customerDebit',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customersmodel',
            name='customerPending',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
    ]
