# Generated by Django 3.0.7 on 2021-04-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0011_auto_20210404_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersmodel',
            name='customerPending',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
