# Generated by Django 3.0.7 on 2021-04-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0013_auto_20210404_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavePdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=120)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='YesMultiServicesLogo',
            fields=[
                ('imageId', models.AutoField(primary_key=True, serialize=False)),
                ('imageName', models.CharField(max_length=120)),
                ('imageLogo', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
