# Generated by Django 3.0.7 on 2021-04-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodel',
            name='businessCreatedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='businessmodel',
            name='businessUpdatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
